Feature/uu course descriptions
CentreForDigitalHumanities/I-analyzer pull request #1722
Opened 2024-12-04 16:20 UTC by lukavdplas

Adds several corpora with UU course descriptions.

I've kept the old "humanities course descriptions" corpus, because that one uses a slightly different data format. That corpus is kept the same, but uses the same picture as the "updated" version.

Because these corpora are created for a separate server, there are a few minor changes to the frontend to configure the server in `environment.ts`:
- Added configuration for the brand (logo / title) shown in the navbar
- You can hide the corpus filters on the home page. This makes sense if, like here, the corpora on the server are very uniform so there is nothing to filter on.

## Server configuration changes

- If a server was using the `hum_course_descriptions` corpus, it must update the location of the source file. It's now located in the `uu_course_descriptions` module.
- Servers must update the `environment.ts` file to specify the `navbarBrand` setting.

2024-12-18 17:04 UTC, Meesch requested changes
Looks very nice, especially the landing page with all the faculties: great job! Got some small stuff and some comments, I tested only using the web app on the server.

2024-12-18 17:04 UTC, Meesch commented on frontend/src/app/menu/menu.component.ts
> +        return ! this.appName.toLowerCase().includes('i-analyzer');
I like the solution stylistically, but I don't know if this is the best way to implement naming conventions. I would either add some documentation explaining how the naming of apps works and how a developer should use those values, or just give two fields in the environment for Main app name and Secondary App name or something? Or is this meant to enforce that we have the I-analyzer name present at all times? :p

2025-01-15 13:47 UTC, lukavdplas commented on frontend/src/app/menu/menu.component.ts
> +        return ! this.appName.toLowerCase().includes('i-analyzer');
Fair point, a primary / secondary name would make more sense!

2025-01-15 13:56 UTC, lukavdplas commented on backend/corpora/uu_course_descriptions/uu_course_descriptions.py
> +            search_filter=MultipleChoiceFilter(option_count=100),
It does? At least for me:

![screenshot of "department" filter in I-analyzer](https://github.com/user-attachments/assets/05a63dc0-ce3b-43de-af36-98fa993d236a)

The CSV column name is misleading, though, maybe you missed it?

2025-02-06 15:40 UTC, merged